# Generated by Django 3.0.3 on 2020-11-12 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20201112_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
