# Generated by Django 3.0.3 on 2021-02-28 15:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of each entry', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumb_nail', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('thumb_nail_x_position', models.IntegerField(default=50)),
                ('thumb_nail_y_position', models.IntegerField(default=50)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('views_per_day', models.PositiveIntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, null=True, to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UrlHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViewsPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('entry', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
                ('url_hit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.UrlHit')),
            ],
        ),
    ]
