# Generated by Django 3.0.3 on 2020-11-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
