# Generated by Django 3.0.3 on 2020-11-12 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patchnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='patch_notes',
        ),
        migrations.AddField(
            model_name='homepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
