# Generated by Django 3.0.3 on 2020-11-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201112_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Text',
        ),
    ]
