# Generated by Django 3.0.3 on 2020-11-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201112_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Info',
        ),
    ]
