# Generated by Django 3.0.3 on 2020-11-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201112_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patchnotes',
            new_name='PatchNote',
        ),
    ]
